events {
  worker_connections 10240;
}

http {
  server {
    listen 80;

    location /api/ {
      proxy_pass http://backend/api/;
    }

    location / {
      proxy_pass http://frontend;
    }
  }
<<<<<<< HEAD
}
=======
}
>>>>>>> 49891b01c20e2297f86d6e3c9fdb119469badc5a
