name: Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'fe/**'

permissions: write-all

jobs: 
  build-and-push-fe:
    name: Build, Test and Push Docker Image FE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./fe

      - name: Run frontend tests
        run: yarn test --watchAll=false
        working-directory: ./fe

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build FE Docker Image
        run: docker build -t tranngobichdu/toeic-learning-website:v1 -f .deploy/fe/Dockerfile .
